# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"color2num": "00_utils.ipynb",
         "colorize": "00_utils.ipynb",
         "calc_logstd_anneal": "00_utils.ipynb",
         "save_frames_as_gif": "00_utils.ipynb",
         "conv2d_output_size": "00_utils.ipynb",
         "num2tuple": "00_utils.ipynb",
         "conv2d_output_shape": "00_utils.ipynb",
         "convtransp2d_output_shape": "00_utils.ipynb",
         "Saver": "00_utils.ipynb",
         "PolicyGradientRLDataset": "01_datasets.ipynb",
         "QPolicyGradientRLDataset": "01_datasets.ipynb",
         "PGBuffer": "02_buffers.ipynb",
         "ReplayBuffer": "02_buffers.ipynb",
         "MLP": "03_neuralnets.ipynb",
         "Actor": "03_neuralnets.ipynb",
         "CategoricalPolicy": "03_neuralnets.ipynb",
         "GaussianPolicy": "03_neuralnets.ipynb",
         "ActorCritic": "03_neuralnets.ipynb"}

modules = ["utils.py",
           "datasets.py",
           "buffers.py",
           "neuralnets.py"]

doc_url = "https://jfpettit.github.io/rl_bolts/"

git_url = "https://github.com/jfpettit/rl_bolts/tree/master/"

def custom_doc_links(name): return None
