# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"color2num": "00_utils.ipynb",
         "colorize": "00_utils.ipynb",
         "calc_logstd_anneal": "00_utils.ipynb",
         "save_frames_as_gif": "00_utils.ipynb",
         "conv2d_output_size": "00_utils.ipynb",
         "num2tuple": "00_utils.ipynb",
         "conv2d_output_shape": "00_utils.ipynb",
         "convtransp2d_output_shape": "00_utils.ipynb",
         "Saver": "00_utils.ipynb",
         "printdict": "00_utils.ipynb",
         "PolicyGradientRLDataset": "01_datasets.ipynb",
         "QPolicyGradientRLDataset": "01_datasets.ipynb",
         "PGBuffer": "02_buffers.ipynb",
         "ReplayBuffer": "02_buffers.ipynb",
         "MLP": "03_neuralnets.ipynb",
         "CNN": "03_neuralnets.ipynb",
         "Actor": "03_neuralnets.ipynb",
         "CategoricalPolicy": "03_neuralnets.ipynb",
         "GaussianPolicy": "03_neuralnets.ipynb",
         "ActorCritic": "03_neuralnets.ipynb",
         "MLPQActor": "03_neuralnets.ipynb",
         "MLPQFunction": "03_neuralnets.ipynb",
         "actor_critic_value_loss": "04_losses.ipynb",
         "reinforce_policy_loss": "04_losses.ipynb",
         "a2c_policy_loss": "04_losses.ipynb",
         "ppo_clip_policy_loss": "04_losses.ipynb",
         "ddpg_policy_loss": "04_losses.ipynb",
         "ddpg_qfunc_loss": "04_losses.ipynb",
         "td3_policy_loss": "04_losses.ipynb",
         "td3_qfunc_loss": "04_losses.ipynb",
         "sac_policy_loss": "04_losses.ipynb",
         "sac_qfunc_loss": "04_losses.ipynb",
         "ToTorchWrapper": "05_env_wrappers.ipynb",
         "StateNormalizeWrapper": "05_env_wrappers.ipynb",
         "RewardScalerWrapper": "05_env_wrappers.ipynb",
         "BestPracticesWrapper": "05_env_wrappers.ipynb",
         "polgrad_interaction_loop": "06_loops.ipynb",
         "PPO": "07_algorithms.ipynb"}

modules = ["utils.py",
           "datasets.py",
           "buffers.py",
           "neuralnets.py",
           "losses.py",
           "env_wrappers.py",
           "loops.py",
           "algorithms.py"]

doc_url = "https://jfpettit.github.io/rl_bolts/rl_bolts/"

git_url = "https://github.com/jfpettit/rl_bolts/tree/master/"

def custom_doc_links(name): return None
