wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
batch_size:
  desc: null
  value: 4000
clipratio:
  desc: null
  value: 0.2
env:
  desc: null
  value: AntBulletEnv-v0
gamma:
  desc: null
  value: 0.99
hidden_sizes:
  desc: null
  value:
  - 32
  - 32
lam:
  desc: null
  value: 0.97
maxkl:
  desc: null
  value: 0.01
pol_lr:
  desc: null
  value: 0.0003
train_iters:
  desc: null
  value: 80
val_lr:
  desc: null
  value: 0.001
